### ISSUE TITLE
Rendor Error with Reanimated 2.4

### ISSUE THREAD

**Issue by DenisFanteria** [craftzdog/react-native-checkbox-reanimated#3]
First sorry for my bad english. With Reanimated 2.4 you get the error :
![Capture d’écran 2022-02-27 à 15 12 30](https://user-images.githubusercontent.com/67110836/155885916-4267cef2-81aa-432e-bb3c-276b8130235e.png)
 
The issue is track here https://github.com/software-mansion/react-native-reanimated/issues/2766.

An esay fix is to change our function from bezier() to bezierFn() in anmiated-stroke.tsx and index.tsx

Hope it will help!

**Comment by DenisFanteria** [comment]
After changing to BezierFn(
![Capture d’écran 2022-02-27 à 15 14 38](https://user-images.githubusercontent.com/67110836/155885977-f8478730-5fb2-44cd-9d2a-e8788b0e4be9.png)
)

**Comment by craftzdog** [comment]
Thanks for the report! Can you make a PR?

**Comment by DenisFanteria** [comment]
i tried to but i get this error : 
ERROR: Permission to craftzdog/react-native-checkbox-reanimated.git denied to DenisFanteria.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have my SSH key in my profile.

I don't understand this is my first PR

**Comment by craftzdog** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by DenisFanteria** [comment]
Thanks for the help and your amazing videos 👍 PR send.
Sorry it's my first time sending a PR.

**Comment by craftzdog** [comment]
Thanks!

**Comment by kokosky93** [comment]
Hi @DenisFanteria can you please tell me which package versions you are using. I had the same issue with reanimated package and many other issues when looking for the package version that will work for me. I am not able to use reanimated library with expo.

**Comment by DenisFanteria** [comment]
Hi @kokosky93 . Take a look at package.json.
